name: alleralert_app
description: "An allergy tracking application with air quality monitoring."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.3

  # UI and utilities
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

  # Authentication
  google_sign_in: ^6.2.2

  # Location and permissions
  geolocator: ^10.1.0
  permission_handler: ^10.2.0

  # Networking
  http: ^1.1.0

  # Speech recognition
  speech_to_text: ^6.6.0

  # Bluetooth functionality (from flutter_bluetooth)
  flutter_blue_plus: ^1.5.2

  # State management
  get: ^4.6.1

  # Data visualization
  syncfusion_flutter_charts: ^27.1.50
  fl_chart: ^0.69.0

  # Math and vectors
  vector_math: ^2.1.4

  # Localization and formatting
  intl: ^0.19.0

  # Machine learning
  dbscan: ^0.1.1
  ml_algo: ^16.17.7

  # File operations
  path_provider: ^2.0.15

  # Sharing
  share_plus: ^7.0.0

  # Logging
  logger: ^1.1.0

  # Collections
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/lungs_logo.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/city_skyline.png
    - assets/images/community.png
    - assets/images/weather.png
    - assets/dbscan_model.onnx
    - assets/scaler_params.json
    - assets/sample_predictions.json

# Add this section to allow mixed mode compilation
dependency_overrides:
  dbscan: ^0.1.1