// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI22K6nDTY62c-TFoRhhYSGGcA7rBZUQg',
    appId: '1:172461007999:web:7e11e7eb75018f6cf80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    authDomain: 'alleralert-app.firebaseapp.com',
    storageBucket: 'alleralert-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfS1jMTB4DVE-eI35sEayIqRG1Wakyjw',
    appId: '1:172461007999:android:26f0bb82eb1d4000f80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    storageBucket: 'alleralert-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJ8_gEd3KbB7lhU3ms4HVcwvjVY69sCU',
    appId: '1:172461007999:ios:8a15120e5cf86fe9f80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    storageBucket: 'alleralert-app.firebasestorage.app',
    iosBundleId: 'com.example.alleralertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJ8_gEd3KbB7lhU3ms4HVcwvjVY69sCU',
    appId: '1:172461007999:ios:8a15120e5cf86fe9f80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    storageBucket: 'alleralert-app.firebasestorage.app',
    iosBundleId: 'com.example.alleralertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI22K6nDTY62c-TFoRhhYSGGcA7rBZUQg',
    appId: '1:172461007999:web:c5577b49f84fa8bff80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    authDomain: 'alleralert-app.firebaseapp.com',
    storageBucket: 'alleralert-app.firebasestorage.app',
  );
}
