// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for your app
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web configuration
      return const FirebaseOptions(
        apiKey: 'AIzaSyByfS1jMTB4DVE-eI35sEayIqRG1Wakyjw',
        appId: '1:172461007999:web:YOUR_WEB_APP_ID', // Replace with actual web appId if you have one
        messagingSenderId: '172461007999',
        projectId: 'alleralert-app',
        storageBucket: 'alleralert-app.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: 'AIzaSyByfS1jMTB4DVE-eI35sEayIqRG1Wakyjw',
          appId: '1:172461007999:android:26f0bb82eb1d4000f80b4a', // Using Android appId as placeholder
          messagingSenderId: '172461007999',
          projectId: 'alleralert-app',
          storageBucket: 'alleralert-app.firebasestorage.app',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfS1jMTB4DVE-eI35sEayIqRG1Wakyjw',
    appId: '1:172461007999:android:26f0bb82eb1d4000f80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    storageBucket: 'alleralert-app.firebasestorage.app',
  );

  // iOS options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfS1jMTB4DVE-eI35sEayIqRG1Wakyjw', // Using Android API key, replace if you have iOS-specific key
    appId: '1:172461007999:ios:8a15120e5cf86fe9f80b4a',
    messagingSenderId: '172461007999',
    projectId: 'alleralert-app',
    storageBucket: 'alleralert-app.firebasestorage.app',
    iosClientId: '172461007999-if2rm3rv2dbs604hv5ehubfivs87blkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.alleralertApp',
  );
}